# Set site parameters
SITE_NAME = 'imap-search-scout'
SITE_VERSION = '0.9.0'
# Set person parameters
EMAIL_LENGTH_MAXIMUM = 48
NICKNAME_LENGTH_MINIMUM = 3
NICKNAME_LENGTH_MAXIMUM = 32
USERNAME_LENGTH_MINIMUM = 6
USERNAME_LENGTH_MAXIMUM = 32
PASSWORD_LENGTH_MINIMUM = 6
PASSWORD_LENGTH_AVERAGE = 16
PASSWORD_LENGTH_MAXIMUM = 32
TICKET_LENGTH = 32
TICKET_LIFESPAN_IN_DAYS = 1
REJECTION_LIMIT = 3
MINUTES_OFFSET_DEFAULT = 240
# Set mail account lengths
HOST_LENGTH_MAXIMUM = 32
# Set mail message lengths
HOST_LENGTH_MAXIMUM = 32
TAG_LENGTH_MAXIMUM = 128
SUBJECT_LENGTH_MAXIMUM = 256
WHOM_LENGTH_MAXIMUM = 128
ATTACHMENT_EXTENSION_LENGTH_MAXIMUM = 16
# Set format parameters
RESULTS_PER_PAGE = 10
# Set mail constants
FOLDER_REVIVED = 'Revived'
EXCLUDED_TAGS = 'Deleted Items', 'Drafts', 'Trash', FOLDER_REVIVED
