python extractOutlook.py mirror ">  >  >  1.0FY09 0701-123108 Tempfiles"
python extractOutlook.py mirror ">  >  >  1.1FY09 Inbox 0101 to 063009 Tempfiles"
python extractOutlook.py mirror ">  >  >  1.1FY09 Sent 0101 to 063009 Tempfiles"
python extractOutlook.py mirror ">  >  >  FY09 Case-level Overflow"
python extractOutlook.py mirror ">>>>Boilerplates & Working Texts"
python extractOutlook.py mirror ">>>>IIAs_Firms_Corps&Mktg"
python extractOutlook.py mirror ">>>>INVENTORS A-B"
python extractOutlook.py mirror ">>>>INVENTORS C-D"
python extractOutlook.py mirror ">>>>INVENTORS Crouse"
python extractOutlook.py mirror ">>>>INVENTORS E-M"
python extractOutlook.py mirror ">>>>INVENTORS N-Z"
python extractOutlook.py mirror ">>>>INVENTORS SHINNAR"
python extractOutlook.py mirror ">>>>OPERATIONS"
